In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

1. Create Your Personal Matrix
Let:
● d1 = last digit of your student ID
● d2 = second last digit of your student ID

In [3]:
import numpy as np

# Given values
d1 = 0
d2 = 2

# Create Matrix A
A = np.array([[d1+2, d2+1],[2*d1, d2+2]])

print("Matrix A:",A)


Matrix A: [[2 3]
 [0 4]]


2. Analyze Matrix A
Using NumPy, compute:
● Shape of A
● Determinant
● Rank
● Eigenvalues
● Inverse (only if determinant ≠ 0)

In [5]:

d1 = 0
d2 = 2
A = np.array([[d1+2, d2+1],[2*d1, d2+2]])

size_A=np.shape(A)
det_A=np.linalg.det(A)
rank_A=np.linalg.matrix_rank(A)
eigenvalues=np.linalg.eig(A)
if np.linalg.det(A) != 0:
    print("Inverse:\n", np.linalg.inv(A))
else:
    print("Inverse: Not possible (determinant is 0)")

#display results

print("Shape:", size_A)
print("Determinant:", np.linalg.det(A))
print("Rank:", np.linalg.matrix_rank(A))
print("Eigenvalues:", np.linalg.eigvals(A))

Inverse:
 [[ 0.5   -0.375]
 [ 0.     0.25 ]]
Shape: (2, 2)
Determinant: 7.999999999999998
Rank: 2
Eigenvalues: [2. 4.]


3. Value Change Experiment
Create a new matrix B by changing exactly one value in A:
● Add +1 to one element of your choice
● You must clearly state which element you changed


In [9]:
A = np.array([[2, 3],[0, 4]])

B = A.copy()
B[1,0] = B[1,0] + 1

print("\nMatrix B (changed A[1,0] by +1):")
print(B)


Matrix B (changed A[1,0] by +1):
[[2 3]
 [1 4]]


4. Compute the same properties as in Step 2.

In [10]:

size_B=np.shape(B)
det_B=np.linalg.det(B)
rank_B=np.linalg.matrix_rank(B)
eigenvalues=np.linalg.eig(B)
if np.linalg.det(B) != 0:
    print("Inverse:\n", np.linalg.inv(B))
else:
    print("Inverse: Not possible (determinant is 0)")

#display results

print("Shape:", size_B)
print("Determinant:", np.linalg.det(B))
print("Rank:", np.linalg.matrix_rank(B))
print("Eigenvalues:", np.linalg.eigvals(B))

Inverse:
 [[ 0.8 -0.6]
 [-0.2  0.4]]
Shape: (2, 2)
Determinant: 5.000000000000001
Rank: 2
Eigenvalues: [1. 5.]


5.Explain these four:

1. Determinant change and why:

Ans: The determinant changed because one of the values in the matrix was modified. Since the determinant depends on all the elements of the matrix, even a small change in one entry can increase or decrease its value.

2. Did the rank change? Explain.

Ans: No, the rank usually stays the same if the rows and columns are still independent after the change. Since only a value was adjusted (and no row became a copy or multiple of another), the rank likely did not change.

3. How did the eigenvalues respond to the value change?

Ans: The eigenvalues also changed because they depend on the matrix entries. When one number in the matrix was changed, the eigenvalues shifted slightly, reflecting the new structure of the matrix.

4. Is B easier or harder to invert than A? Why?

Ans: Matrix B is harder to invert if its determinant is closer to zero, because that makes the inverse less stable and more sensitive to small changes. If B has a larger determinant than A, then it is easier to invert.